services:
  - type: web
    name: baby-bliss-backend
    runtime: php
    rootDir: api
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT index.php
    envVars:
      - key: DB_HOST
        value: # Set your MySQL host
      - key: DB_USER
        value: # Set your MySQL user
      - key: DB_PASS
        value: # Set your MySQL password
      - key: DB_NAME
        value: # Set your MySQL database name
